name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8  # Optional (for iOS icons)
  http: ^1.1.0  # For API calls
  shared_preferences: ^2.2.2  # For storing auth tokens
  provider: ^6.1.0  # For state management
  flame: ^1.21.0 # Game Engine
  rive: ^0.13.15 # Animations
  flame_rive: ^1.10.0 # Rive integration for Flame

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  # ✅ Needed for Icons.star_rounded
  assets:
    - assets/rive/
